### ISSUE TITLE
Колонка с логотипами игр слишком широкая

### ISSUE THREAD

**Issue by iVAN2002** [Newbilius/GamesRevivalSiteGenerator#4]
https://www.gamesrevival.ru/games.html
![2019-02-14_19-25-16](https://user-images.githubusercontent.com/6745157/52801337-b021b880-308e-11e9-8763-a9a423908b15.png)
Nuff said
Chrome 72, Win8.1

**Comment by Newbilius** [comment]
Оппа, в Chrome и правда глючит. Спасибо, будут фиксить!
Любовь к Firefox меня подводит - там выглядит вот так:

![screenshot_1](https://user-images.githubusercontent.com/2031614/52802035-e6683380-30a0-11e9-8a38-7cf7088dbded.png)

**Comment by Newbilius** [comment]
Поправил
